http:
  middlewares:
    authelia:
      forwardAuth:
        address: 'http://authelia:9091/api/verify?rd=https://auth.{{ env "HOST" }}'
        trustForwardHeader: true
        authResponseHeaders: Remote-User,Remote-Groups,Remote-Name,Remote-Email
    secure-headers:
      headers:
        # stsSeconds: 31536000
        # stsIncludeSubdomains: true
        contentTypeNosniff: true
        browserXssFilter: true
        contentSecurityPolicy: 'frame-ancestors {{ env "HOST" }}'
        referrerPolicy: "same-origin"
    gzip:
      compress: {}
    crowdsec:
      plugin:
        crowdsec-bouncer:
          enabled: true
          crowdseclapikey: '{{ env "BOUNCER_KEY_TRAEFIK" }}'
